auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Seikinmeid's Blog
url: http://seikinmeid.github.io
feed: /atom.xml
author_info: <a href="http://seikinmeid.github.io">Seikinmeid</a>
